# Generated by Django 4.0.2 on 2022-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('username', models.CharField(max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
